export class UserInfo {
  userId: string = '';
  userName: string = '';
  emailAddress: string = '';
  fullName: string = '';
  departmentId: string = '';
  authToken: string = '';
  authTokenExpiry: string = '';
  departmentName: string = '';
  departmentCreatedOn: string = '';
  enableDetailedResponses: boolean = false;
  enablePushNotifications: boolean = false;
  pushRegistrationId: string = '';
  personnelFilter: string = '';
  unitsFilter: string = '';
  sortRespondingTop: boolean = false;
  enableCustomSounds: boolean = false;
  enableGeolocation: boolean = false;
  language: string = '';
  enableSounds: boolean = false;
  enableLiveUpdates: boolean = false;
  lastSynced: string = '';
  pushRegisteredOn: string = '';
  customUrl: string = '';
  customUrlValidated: boolean = false;
}
