export class CallResultData {
  public CallId: string = '';
  public Priority: number = 0;
  public Name: string = '';
  public Nature: string = '';
  public Note: string = '';
  public Address: string = '';
  public Geolocation: string = '';
  public LoggedOn: string = '';
  public State: string = '';
  public Number: string = '';
  public NotesCount: number = 0;
  public AudioCount: number = 0;
  public ImgagesCount: number = 0;
  public FileCount: number = 0;
  public What3Words: string = '';
  public ContactName: string = '';
  public ContactInfo: string = '';
  public ReferenceId: string = '';
  public ExternalId: string = '';
  public IncidentId: string = '';
  public AudioFileId: string = '';
  public Type: string = 'No Type';
  public LoggedOnUtc: string = '';
  public DispatchedOn: string = '';
  public DispatchedOnUtc: string = '';
  public Latitude: string = '';
  public Longitude: string = '';
}
